### ISSUE TITLE
support for java 8 lambda expressions

### ISSUE THREAD

**Issue by ichernev** [musiKk/plyj#30]
Support lambda expressions from java 8. The grammer can be snatched from antlr's java 8 grammar file: https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4

```java
package com.example.java8;


import java.util.function.Supplier;

public class Main {


    public static void main(String[] args) throws Exception {
        Supplier<Integer> s = (() -> { return 42; });
    }

}
```

fails with
```python
>>> import plyj.parser as plyj
>>> parser = plyj.Parser()
>>> tree = parser.parse_file(file('path/to/Main.java'))
error: LexToken(),')',10,184)
```

**Comment by musiKk** [comment]
plyj currently only supports Java 7. I actually wanted to do this for quite a while but never really came around to.

I'll look into it.

**Comment by musiKk** [comment]
Actually it's much crazier than I thought. Some features are quite easy but currently I'm stuck with lambdas. JDT intentionally leaves some ambiguities in the grammar (probably for performance reasons) and resolves them by creating a nested parser that just tries a few things until something parses (they call it `VanguardParser`). I don't see how this would work with PLY.

I'm also not sure if I can use the linked grammar from ANTLR because it uses LL(*) whereas PLY utilizes LALR(1).

**Comment by musiKk** [comment]
Closing this in favor of a more general Java 8 issue (#40).
